name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

#filter-by-commitish: true
#commitish: release_v**

template: |
  ## What’s Changed
  
  $CHANGES
# Changelog definitions

sort-by: 'merged_at'
sort-direction: 'descending'
exclude-labels:
  - 'changelog/exclude'

# Change definitions
no-changes-template: "* No changes"
change-template: "* [#$NUMBER] $TITLE - @$AUTHOR"
change-title-escapes: '\<*_&'

# Versioning definitions
version-resolver:
  default: 'patch'
