name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

autolabeler:
  - label: 'hotfix'
    branch:
      - 'release_v**'

include-labels:
  - 'hotfix'

template: |
  ## Hotfix Changes
  
  $CHANGES
# Changelog definitions

sort-by: 'merged_at'
sort-direction: 'descending'

# Change definitions
no-changes-template: "* No changes"
change-template: "* [#$NUMBER] $TITLE - @$AUTHOR"
change-title-escapes: '\<*_&'

# Versioning definitions
version-resolver:
  default: 'patch'
