name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

filter-by-commitish: true

template: |
  ## Hotfix Changes
  
  $CHANGES
# Changelog definitions

sort-by: 'merged_at'
sort-direction: 'descending'
exclude-labels:
  - 'changelog/exclude'

# Change definitions
no-changes-template: "* No changes"
change-template: "* [#$NUMBER] $TITLE - @$AUTHOR"
change-title-escapes: '\<*_&'

# Versioning definitions
version-resolver:
  default: 'patch'
