# This is a basic workflow to help you get started with Actions

name: Deploy Server Hotfix
  # Allows you to run this workflow manually from the Actions tab

on:
  workflow_dispatch:
    inputs:
      application:
        type: choice
        description: Select the app to deploy
        required: true
        options:
          - eblock-graphql
          - eblock-scheduler
          - eblock-netsuite
          - eblock-auction-runner
          - eblock-netsuite
          - eblock-integrations
      node:
        type: choice
        description: Server Node
        options:
          - NODE1_HOST
          - NODE2_HOST
      tag:
        required: true
        description: Tag to deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download server asset
        id: download_server_asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ github.event.inputs.tag }}
          file: server.jar
          target: server.jar

      - name: Send greeting
        run: echo "${{ github.event.inputs.tag }} ${{ github.event.inputs.node }} ${{ github.event.inputs.application }}"