# This is a basic workflow to help you get started with Actions

name: Deploy Server

# Controls when the workflow will run
on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download server asset
        id: download_server_asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ github.event.release.tag_name }}
          file: server.jar
          target: server.jar

      - name: create pull request
        run: git checkout -b release_${{ github.event.release.tag_name }} && git push origin release_${{ github.event.release.tag_name }}
