# This is a basic workflow to help you get started with Actions

name: deploy-prod

# Controls when the workflow will run
on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download server asset
        id: download_server_asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ github.event.release.tag_name }}
          file: propsbuddy.jar
          target: propsbuddy.jar

      - name: Download web app assets
        id: download_webapp_asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ github.event.release.tag_name }}
          file: dist.zip
          target: dist.zip
        
      - name: Upload assets to environment
        id: upload_server_assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "propsbuddy.jar, dist.zip"
          target: ~/assets
          overwrite: true
          rm: true
        
      - name: Deploy server assets
        id: deploy_server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /opt/propsbuddy/propsbuddy.jar /opt/propsbuddy/old_propsbuddy.jar && \
            sudo cp ~/assets/propsbuddy.jar /opt/propsbuddy/ && \
            sudo systemctl restart propsbuddy.service

      - name: Deploy UI assets
        id: deploy_ui
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -r /var/www/propsbuddy.com/dist_old && \
            sudo mv /var/www/propsbuddy.com/dist /var/www/propsbuddy.com/dist_old && \
            sudo rm -rf /var/www/propsbuddy.com/dist && \
            sudo cp -r ~/assets/dist.zip /var/www/propsbuddy.com/ && \
            sudo unzip -o /var/www/propsbuddy.com/dist.zip -d /var/www/propsbuddy.com/. && \
            sudo service apache2 reload
