name: build-artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v3

      - name: Draft new release
        id: draft_release
        uses: release-drafter/release-drafter@v5.21.1
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PERSONAL_TOKEN }}
