# This is a basic workflow to help you get started with Actions

name: Release Notes

# Controls when the workflow will run
on:
  # Triggers the workflow on publish of Release in Pre-release state
  release:
    types: [ prereleased ]


jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Parse release body for release notes and extract JIRA ticket numbers
      # Search for regex EB-XXXX and then outputs the ticket numbers separated by commas
      - name: Run a multi-line script
        id: parse-release-notes
        run: |
          releaseBody=$(echo '${{ github.event.release.body }}')
          echo "::set-output name=tickets::$(echo $releaseBody | grep -o 'PB-[0-9]*' | tr '\n' ',')"
            
      # Runs a set of commands using the runners shell
      - name: Send ticket numbers to JIRA release
        run: |
          echo Tickets associated with release
          echo ${{ steps.parse-release-notes.outputs.tickets }}
          
          
      - name: Release Jira Version
        uses: armona/jira-release-actions@v2.0.6
        with:
          email: ${{ secrets.JIRA_EMAIL }}
          api_token: ${{ secrets.JIRA_TOKEN }}
          subdomain: ryanchristilaw
          jira_project: PB
          release_name: ${{ github.event.release.name }}
          create: true
          release: false
#          tickets: ${{ steps.parse-release-notes.outputs.tickets }}
